# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# mesoModel.py
# Created on: 2013-11-18 12:54:51.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy


# Local variables:
mesonet = "mesonet"
Oklahoma = "Oklahoma"
buffers30k_shp = "C:\\pyWork\\instructor\\countyChaos\\buffers30k.shp"
distantLands_shp = "C:\\pyWork\\instructor\\countyChaos\\distantLands.shp"

# Process: Buffer
arcpy.Buffer_analysis(mesonet, buffers30k_shp, "30 Kilometers", "FULL", "ROUND", "ALL", "")

# Process: Erase
arcpy.Erase_analysis(Oklahoma, buffers30k_shp, distantLands_shp, "")

