# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# mesoModel2.py
# Created on: 2016-01-26 09:47:11.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy


# Local variables:
inputShp = "c:/pyWork/day2/countyChaos/Oklahoma.shp"
mesonet = "c:/pyWork/day2/countyChaos/mesonet.shp"
mesonet_Buffer_shp = "C:/pyWork/day2/countyChaos/mesonet_Buffer.shp"
Oklahoma_Erase_shp = "C:/pyWork/day2/countyChaos/Oklahoma_Erase.shp"

# Set Geoprocessing environments
arcpy.env.scratchWorkspace = "C:/pyWork/day2/countyChaos"
arcpy.env.workspace = "C:/pyWork/day2/countyChaos"
arcpy.env.overwriteOutput = True

# Process: Buffer
arcpy.Buffer_analysis(mesonet, mesonet_Buffer_shp, "30 Kilometers", "FULL", "ROUND", "ALL", "", "PLANAR")

# Process: Erase
arcpy.Erase_analysis(inputShp, mesonet_Buffer_shp, Oklahoma_Erase_shp, "")

